language: node_js
sudo: true
dist: trusty

jobs:
  include:
    - stage: Build
      install:
        npm install
  include:
    - stage: Test
      install:
        npm test
  include:
    - stage: Container
      script: sh build.sh container