language: node_js
sudo: required
dist: trusty

jobs:
  include:
    - stage: Build
      install:
        npm install
  include:
    - stage: Test
      install:
        npm test
  include:
    - stage: Container
      script: sh source ~/.bashrc && cd Central && sh build.sh container